---
- name: Login to EVE-NG and Start a Lab
  hosts: localhost
  gather_facts: no
  vars:
    eve_ng_host: "10.236.73.64"  # Replace with your EVE-NG host address
    eve_ng_username: "admin"  # Replace with your EVE-NG username
    eve_ng_password: "eve"  # Replace with your EVE-NG password
    lab_path: "/opt/unetlab/labs/BGP_Neighbor_Adj.unl"  # Replace with the path to your lab

  tasks:
    - name: Login to EVE-NG and retrieve auth token
      uri:
        url: "http://{{ eve_ng_host }}/api/auth/login"
        method: POST
        body_format: json
        body: 
          username: "{{ eve_ng_username }}"
          password: "{{ eve_ng_password }}"
        headers:
          Content-Type: "application/json"
        return_content: yes
        validate_certs: no
      register: login_response

    - name: Set unetlab_session cookie as a fact
      set_fact:
        eve_ng_session_cookie: "{{ login_response.cookies.unetlab_session }}"

    - name: Start the lab in EVE-NG using the session cookie
      uri:
        url: "http://{{ eve_ng_host }}/api/{{ lab_path }}/start"
        method: POST
        headers:
          Cookie: "unetlab_session={{ eve_ng_session_cookie }}"
        status_code: 200
        body_format: json
      register: start_lab_response

    - name: Print response for debugging
      debug:
        var: start_lab_response

    - name: Start all nodes in the lab
      uri:
        url: "http://{{ eve_ng_host }}/api/labs{{ lab_path }}/nodes/start"
        method: POST
        headers:
          Cookie: "unetlab_session={{ eve_ng_session_cookie }}"
        status_code: 200
        body_format: json
      register: start_nodes_response

   - name: Print response for starting nodes
     debug:
       var: start_nodes_response



  
    

